.\"	$OpenBSD: mdoc.template,v 1.15 2014/03/31 00:09:54 dlg Exp $
.\"
.\" Copyright (c) 2021 Guilherme Janczak <guilherme.janczak@yandex.com
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: December 15 2021 $
.Dt DICTPW 1
.Os
.Sh NAME
.Nm dictpw
.Nd dictionary-based password generation program
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl n Ar MIN_WORD <= word_count <= MAX_WORD
.Sh DESCRIPTION
The
.Nm
utility generates a dot-separated password composed of random words taken from
the
.Lk https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases EFF Long Wordlist .
.Bl -tag -width Ds
.It Fl h
Show the synopsis and the limits of
.Fl n .
.It Fl n Ar word_count
Change the default word count of the password, more words is more secure.
The program rejects values that are nonsensically small or large.
.El
.Sh STANDARDS
.Lk https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt EFF's long word list .
.Sh AUTHORS
.An Guilherme Janczak Aq Mt guilherme.janczak@yandex.com .
