.\"	$OpenBSD: mdoc.template,v 1.15 2014/03/31 00:09:54 dlg Exp $
.\"
.\" Copyright (c) 2021-2022, 2024-2025
.\"     Guilherme Janczak <guilherme.janczak@yandex.com
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: January 6 2025 $
.Dt DICTPW 1
.Os
.Sh NAME
.Nm dictpw
.Nd generate password from dictionary
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl n Ar MIN <= count <= MAX
.Sh DESCRIPTION
The
.Nm
utility generates a password composed of random words taken from
the
.Lk https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases EFF Long Wordlist ,
separated by dots.
.Bl -tag -width Ds
.It Fl h
Show the synopsis and the limits of
.Ar count .
.It Fl n Ar count
Change the default word count of the password.
The default is already a cautious value,
and the program rejects values that are nonsensically small or large.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Unix usage:
.Dl $ dictpw
.Pp
Windows users can always call
.Nm
using the the App Paths shortcut.
PowerShell:
.Dl PS C:\eUsers\efoo> Start-Process -NoNewWindow -Wait dictpw
Batch:
.Dl C:\eUsers\efoo> start /b /wait dictpw
.Pp
If a Windows installation of
.Nm
was done via Chocolatey, or if
.Em Add to $env:PATH
(the default) was selected during installation,
the program can be called normally:
.Dl PS C:\eUsers\efoo> dictpw
.Sh STANDARDS
.Lk https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt EFF's long word list .
.Sh AUTHORS
.An Guilherme Janczak Aq Mt guilherme.janczak@yandex.com .
